version: 2.1

jobs:
  build:
    docker:
        - image: cimg/node:14.18.0
    steps:
      - checkout
      - run:
          name: Show node version
          command: node --version

      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-

      - run:
          name: Install NPM dependencies
          command: npm install

      - save_cache:
          # Cache local dependencies if they don't exist
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Install headless Chrome
          command: curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \  
    && apt-get install -y google-chrome-stable build-essential jq git openssh-server \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


    - run:
          name: Testing
          command: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
