version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.18.0-browsers
    steps:
      - checkout

      - run:
          name: Show node version
          command: node --version

      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-

      - run:
          name: Install NPM dependencies
          command: npm install

      - save_cache:
          # Cache local dependencies if they don't exist
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: set environment variable to locale Chrome binary
          command: export CHROME_BIN=/usr/bin/google-chrome

      - run:
          name: Testing
          command: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
