version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
  heroku: circleci/heroku@1.2.6
  jira: circleci/jira@1.3.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout

      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-

      - run:
          name: Install NPM dependencies
          command: npm install

      - save_cache:
          # Cache local dependencies if they don't exist
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - browser-tools/install-browser-tools:
          firefox-version: 96.0.3

      - run:
          name: Linting
          command: npm run lint

      - run:
          name: Testing
          command: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI

      - heroku/install
      - run:
          name: Building distribution
          command: npm run build -- --aot=true --configuration=production --progress=true
      - run:
          name: Echoing envrironment variables
          command: echo ${HEROKU_API_KEY}
      - heroku/deploy-via-git:
          api-key: HEROKU_API_KEY
          app-name: heroku-expense-tracker-fe
          branch: main

workflows:
  build-frontend:
    jobs:
      - build:
          post-steps:
            - jira/notify:
                token_name: JIRA_TOKEN
