/**
 * Heroku Expense Tracker
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ExpenseCheckedStatusRequest } from '../model/models';
import { ExpenseListResponse } from '../model/models';
import { ExpenseRequest } from '../model/models';
import { ExpenseResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetExpensesRequestParams {
    pageSize: number;
    pageNumber: number;
    sortDirection: 'ASC' | 'DESC';
    sortBy: 'DATE' | 'AMOUNT';
    tagFilters?: Array<string>;
    descriptionFilters?: Array<string>;
    paidWithCreditCardFilter?: boolean;
    creditCardStatementIssuedFilter?: boolean;
    inclusiveDateLowerBound?: string;
    inclusiveDateUpperBound?: string;
    checked?: boolean;
    inclusiveAmountLowerBound?: number;
    inclusiveAmountUpperBound?: number;
}

export interface ImportExpensesRequestParams {
    file?: Blob;
}

export interface RegisterExpenseRequestParams {
    expenseRequest: ExpenseRequest;
}

export interface UpdateExpensesCheckedStatusRequestParams {
    expenseCheckedStatusRequest: ExpenseCheckedStatusRequest;
}


export interface ExpensesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Export expenses
     * Download current user\&#39;s expenses as a CSV file
     * @endpoint get /expenses/back-up
*/
    exportExpenses(extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Retrieve expenses
     * Retrieve expenses belonging to the current user, in a paginated way. This operation also supports filtering based on tag(s) and partial description
     * @endpoint get /expenses
* @param requestParameters
     */
    getExpenses(requestParameters: GetExpensesRequestParams, extraHttpRequestParams?: any): Observable<ExpenseListResponse>;

    /**
     * Import expenses
     * Upload file with expenses to import
     * @endpoint post /expenses/import
* @param requestParameters
     */
    importExpenses(requestParameters: ImportExpensesRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Register an expense.
     * Registers an expense
     * @endpoint post /expenses
* @param requestParameters
     */
    registerExpense(requestParameters: RegisterExpenseRequestParams, extraHttpRequestParams?: any): Observable<ExpenseResponse>;

    /**
     * Update the checked/unchecked status of the specified expenses
     * 
     * @endpoint patch /expenses/checked-status
* @param requestParameters
     */
    updateExpensesCheckedStatus(requestParameters: UpdateExpensesCheckedStatusRequestParams, extraHttpRequestParams?: any): Observable<Array<ExpenseResponse>>;

}
