/**
 * Heroku Expense Tracker
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ExpenseRequest } from '../model/models';
import { ExpenseResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteExpenseRequestParams {
    id: string;
}

export interface GetExpenseRequestParams {
    id: string;
}

export interface UpdateExpenseRequestParams {
    id: string;
    expenseRequest: ExpenseRequest;
}


export interface ExpenseServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete an existing expense
     * Delete the expense that is identified by &#x60;id&#x60;
     * @endpoint delete /expense/{id}
* @param requestParameters
     */
    deleteExpense(requestParameters: DeleteExpenseRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Retrieve an expense based on its identifier
     * Fetch the expense that is identified by &#x60;id&#x60; and belongs to the current user
     * @endpoint get /expense/{id}
* @param requestParameters
     */
    getExpense(requestParameters: GetExpenseRequestParams, extraHttpRequestParams?: any): Observable<ExpenseResponse>;

    /**
     * Update an existing expense
     * Update the expense that is identified by &#x60;id&#x60; and belongs to the current user
     * @endpoint put /expense/{id}
* @param requestParameters
     */
    updateExpense(requestParameters: UpdateExpenseRequestParams, extraHttpRequestParams?: any): Observable<ExpenseResponse>;

}
