/**
 * Heroku Expense Tracker
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Tag } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetTagsRequestParams {
    query?: string;
}


export interface TagsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieve current authenticated user\&#39;s tags
     * Retrieve the tags that belong to the current user and that match the provided query, if there is any
     * @endpoint get /tags
* @param requestParameters
     */
    getTags(requestParameters: GetTagsRequestParams, extraHttpRequestParams?: any): Observable<Array<Tag>>;

}
