/**
 * Heroku Expense Tracker
 * API for Heroku Expense Tracker, a hobby project to manage personal expenses
 *
 * The version of the OpenAPI document: 1.3.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';

/**
 * Representation of an expense that has been persisted in the system.
 */
export interface ExpenseResponse {
  date: string;
  amount: number;
  tags: Array<Tag>;
  description?: string;
  paidWithCreditCard?: boolean;
  creditCardStatementIssued?: boolean;
  version?: number;
  id: string;
  checked: boolean;
}
