/**
 * Heroku Expense Tracker
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';


/**
 * Request object representing an expense to be registered in the application
 */
export interface ExpenseRequest { 
    date: string;
    amount: number;
    tags: Array<Tag>;
    description?: string;
    paidWithCreditCard?: boolean;
    creditCardStatementIssued?: boolean;
    version?: number;
}

