/**
 * Heroku Expense Tracker
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExpenseResponse } from './expense-response';


/**
 * Paginated response that is returned to the user upon retrieval of his expenses
 */
export interface ExpenseListResponse { 
    pageNumber: number;
    pageSize: number;
    totalNumberOfItems: number;
    items: Array<ExpenseResponse>;
}

